---
# tasks file for common

- name: 'Updating hostname and hosts'
  include_tasks:
    file: editing_hostname.yml

- name: 'Setting timezone to: {{ zone }}'
  timezone:
    name: '{{ zone }}'

- name: 'rpms and services'
  include_tasks:
    file: rpms_services.yml

- name: 'SELinux'
  include_tasks:
    file: disable_selinux.yml
