- name: 'Update rpms'
  yum:
    name: '*'
    state: latest
  notify: Reboot

- name: 'Installing rpms: {{rpms}}'
  yum:
    name: '{{ item }}'
    state: latest
  loop: '{{ rpms }}'

- name: 'Starting services: {{ services }}'
  systemd:
    name: '{{ item }}'
    state: started
    enabled: yes
  loop: '{{ services }}'
