- name: 'Kubernetes: Pull images kubeadm requires'
  shell: kubeadm config images pull

- name: 'Kubernetes: Installing plugin CNI'
  shell: kubeadm init --pod-network-cidr='{{ pods_network }}'

- name: 'Kubernetes: Generating token (1/2)'
  shell: kubeadm token create --print-join-command
  register: kubeadm_token

- name: 'Kubernetes: Token to local (2/2)'
  local_action: copy content='{{ kubeadm_token.stdout }}' dest='./roles/worker/files/kubeadm-token'

- name: 'Autorizing cluster access: Create directory ".kube"'
  file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: 0755

- name: 'Autorizing cluster access: Copying "config" file'
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: 0755
