---
# tasks file for master

- name: 'Configuring Firewall'
  include_tasks:
    file: master_firewall.yml

- name: 'Configuring Kubernetes'
  include_tasks:
    file: config_kubernetes.yml

- name: 'SDN'
  include_tasks:
    file: sdn-local.yml # Change it to "sdn-local.yml" if you want to deploy SDN locally

- name: 'Ingress'
  include_tasks:
    file: ingress.yml
