---
# tasks file for master

- name: 'Ansible: Installing k8s module pre-requisites'
  pip:
    name:
      - openshift
      - pyyaml

- name: 'Firewall'
  include_tasks:
    file: master_firewall.yml

- name: 'Kubernetes'
  include_tasks:
    file: config_kubernetes.yml

- name: 'SDN'
  include_tasks:
    file: sdn.yml # Change it to "sdn-local.yml" if you are doing a local deploy

- name: 'Ingress'
  include_tasks:
    file: ingress.yml
