- name: 'SDN: Downloading manifest'
  get_url:
    url: https://docs.projectcalico.org/manifests/canal.yaml
    dest: /home/{{ ansible_user }}/canal.yaml
    mode: 0664

- name: 'SDN: Aplying Network Politics definition'
  k8s:
    state: present
    src: /home/{{ ansible_user }}/canal.yaml
  become: false
  notify: Reboot
