# Let iptables see bridged traffic

- name: 'Enabling modprobe br_netfilter'
  modprobe:
    name: br_netfilter
    state: present

- name: 'Enabling transparent masquerading'
  firewalld:
    masquerade: yes
    permanent: true
    zone: public
    state: enabled
  notify: Reload Firewall

- name: 'Create|Update sysctl.d/k8s.conf'
  lineinfile:
    dest: /etc/sysctl.d/k8s.conf
    line: '{{item}}'
    state: present
    create: yes
  with_items:
    - '# CP2'
    - 'net.bridge.bridge-nf-call-ip6tables = 1'
    - 'net.bridge.bridge-nf-call-iptables = 1'
    - 'net.ipv4.ip_forward = 1'
  notify: sysctl system

- name: 'Firewall: Open Ports (SDN)'
  firewalld:
    port: '{{item}}'
    permanent: yes
    state: enabled
    immediate: yes
  with_items: '{{ sdn_ports }}'
  notify: Reload Firewall
