---
# tasks file for nodes preconfiguration

- name: 'Configuration: bridged traffic'
  include_tasks:
    file: config_traffic.yml

- name: 'SWAP'
  include_tasks:
    file: disable_swap.yml

- name: 'CRI-O'
  include_tasks:
    file: install_crio.yml

- name: 'Kubernetes'
  include_tasks:
    file: install_kubernetes.yml
